### ISSUE TITLE
shiny codec gui updates

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/codec_data_explorer#1]
- [x] click dot on scatter plot to highlight tract?
- [x] plot colors/legend underneath scatter plot to combine plot and legend; e.g.:

![Image](https://user-images.githubusercontent.com/4367617/234655853-8696b544-bfd5-426d-bd35-2741cfcb85e0.png)

**Comment by andrew-vancil** [comment]
- [ ] toggle switch for a big version of scatter plot
