### ISSUE TITLE
Duplicate titles in metadata

### ISSUE THREAD

**Issue by andrew-vancil** [geomarker-io/codec_data_explorer#3]
I found a little bug in the metadata. There are two items with the same 'title' of "Median Housing Income", one from the hh_acs_measures and one from tract_indices. This is causing an issue when selecting variables in the app. Should we delineate these with more specific names or do we only need this measure once?

**Comment by cole-brokamp** [comment]
good catch.  I think that our specs will not be able to rule this out.  Eventually, there will be column name 'collision' more and more within the combined CoDEC datasets as they grow.  Under the hood, we could combine the tdr name with the field name to create a unique field identifier, but I don't think this will solve the problem of selecting the right variable from the dropdown.  There aren't any hierarchical type of dropdowns are there?

**Comment by cole-brokamp** [comment]
for now, create globally-unique field names by prefixing with codec tdr `name` field.
